apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the DaemonSet instance
  name: my-node-app
spec:
  # The number of Pods to run on each Node
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      # This container is run once on each Node in the cluster
      - name: node-app
        image: abhishekrittu/express-demo-app:01
       

 ---
kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: service-mynode-app
spec:
  ports:
    # Accept traffic sent to port 80
    - name: http
      port: 8080
      targetPort: 3000
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
     app: node-app
  # Create an HA proxy in the cloud provider
  # with an External IP address - *Only supported
  # by some cloud providers*
  type: LoadBalancer
