# Use the official Python image as the base image
FROM python:latest

# Set the working directory inside the container
WORKDIR /app

# Copy the application file into the container
COPY app.py .

# Specify the command to run the application
CMD ["python", "app.py"]
