apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the DaemonSet instance
  name: my-node-app
spec:
  # The number of Pods to run on each Node
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      # This container is run once on each Node in the cluster
      - name: node-app
        image: abhishekrittu/express-demo-app:01
       